name: Helm chart package and bucket push

on:
  push:
    # run when commits are made to the main or specfed branch 
    branches:
      - main

env:
  charts_folder: 'helm-charts'
  cloud_storage_bucket: 'helm-charts-push-2024'

jobs:
  helm-chart-bucket-push:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: '3.5.0'

      - name: Detect changes in helm chart directories
        id: changed
        run: |
              set -xe

              # Get list of changed directories in 'charts' using git diff between current and previous sha
              CHANGED_DIRS=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} -- $charts_folder/ | xargs dirname | sort | uniq)
                          
              if [ -z "$CHANGED_DIRS" ]; then
                echo "No changes in charts directory"
                echo "changed=false" >> "$GITHUB_OUTPUT"
              else
                echo "Changed directories: $CHANGED_DIRS"

                echo "changed=true" >> "$GITHUB_OUTPUT"
                
                # Creating a multiline environment variable using value from $CHANGED_DIRS. Only way to make a multi-line variable work
                echo "CHANGED_DIRS_ENV_VAR<<EOF" >> $GITHUB_ENV
                echo $CHANGED_DIRS >> $GITHUB_ENV
                echo "EOF" >> $GITHUB_ENV

              fi

      - name: Package changed helm charts
        if: steps.changed.outputs.changed == 'true'
        run: |
              set -xe
              
              CHANGED_DIRS="${{ env.CHANGED_DIRS_ENV_VAR }}"
              for dir in $CHANGED_DIRS; do
                if [ -d "$dir" ]; then
                  echo "Packaging chart in $dir"
                  #packaging chart to destination for upload e.g. $chart-upload-folder/<chart folder name>
                  # helm package "$dir" --destination ${{ env.charts_upload_folder }}/$(echo $dir | awk -F'/' '{print $2}')
                  helm package "$dir" --destination "$dir"               
                else
                  echo "$dir is not a directory, skipping"
                fi
              done

      - name: Google authentication for bucket push
        uses: google-github-actions/auth@v0.4.0
        if: steps.changed.outputs.changed == 'true'
        with:
          # credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          create_credentials_file: 'true'       
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: Cloud storage bucket push
        uses: 'google-github-actions/upload-cloud-storage@v2'
        if: steps.changed.outputs.changed == 'true'
        with:
          path: '${{ env.charts_folder }}'
          destination: '${{ env.cloud_storage_bucket }}' 
          # setting parent to false ommits the parent folder specified on the path variable
          parent: false
          glob: '**/*.tgz'

